import {
  Home01Icon,
  UserGroupIcon,
  CheckListIcon,
  Notebook01Icon,
  NewsIcon,
  FolderLibraryIcon,
  Wallet01Icon,
  Invoice01Icon,
  Location01Icon,
  TaskDaily01Icon,
  HealthIcon,
  PrescriptionIcon,
  Calendar03Icon,
  Video01Icon,
  Alert01Icon,
  AnalyticsUpIcon,
  JusticeScale01Icon,
  StethoscopeIcon,
} from '@hugeicons/core-free-icons';

export const ROLE_NAV = {
  admin: [
    { to: '/admin', label: 'Overview', end: true, icon: Home01Icon },
    { to: '/admin/users', label: 'Users', icon: UserGroupIcon },
    { to: '/admin/vetting', label: 'Vetting', icon: CheckListIcon },
    { to: '/admin/disputes', label: 'Disputes', icon: JusticeScale01Icon },
    { to: '/admin/sos', label: 'SOS', icon: Alert01Icon },
    { to: '/admin/analytics', label: 'Analytics', icon: AnalyticsUpIcon },
  ],
  family: [
    { to: '/family/care-plan', label: 'Care plan', end: true, icon: Notebook01Icon },
    { to: '/family/feed', label: 'Care feed', icon: NewsIcon },
    { to: '/family/vault', label: 'Vault', icon: FolderLibraryIcon },
    { to: '/family/wallet', label: 'Wallet', icon: Wallet01Icon },
    { to: '/family/utilities', label: 'Utilities', icon: Invoice01Icon },
    { to: '/family/sessions', label: 'Consults', icon: StethoscopeIcon },
  ],
  caregiver: [
    { to: '/caregiver', label: 'Overview', end: true, icon: Home01Icon },
    { to: '/caregiver/check-in', label: 'Check-in', icon: Location01Icon },
    { to: '/caregiver/tasks', label: 'Tasks', icon: TaskDaily01Icon },
    { to: '/caregiver/vitals', label: 'Vitals', icon: HealthIcon },
    {
      to: '/caregiver/prescriptions',
      label: 'Prescriptions',
      icon: PrescriptionIcon,
    },
    { to: '/caregiver/video', label: 'Video', icon: Video01Icon },
    { to: '/caregiver/payments', label: 'Payments', icon: Wallet01Icon },
  ],
  doctor: [
    { to: '/doctor/sessions', label: 'Video consult', end: true, icon: Video01Icon },
    {
      to: '/doctor/prescriptions',
      label: 'Prescriptions',
      icon: PrescriptionIcon,
    },
    { to: '/doctor/notes', label: 'Session notes', icon: Notebook01Icon },
    { to: '/doctor/availability', label: 'Availability', icon: Calendar03Icon },
    { to: '/doctor/ratings', label: 'Ratings', icon: AnalyticsUpIcon },
  ],
};
